travis:
  secure:
    BINSTAR_TOKEN: tRybQgdrKAIkhy95kPRfIDKF/njMQqz0ezIRXzDsIt5V0ve87uxMM36VhxkbrLVoNpzB9tXdO9IA6hHgulhcY/J4lDgKJW9eNSnFLVm4IXQIPzJzpPYZqc5xQiQpxR99tC5AcjZOYiwM6BMY+AGjJcDTYu+5UI3WaR2/Ew/Azr0XX4WOcV8gl2geg4CHpgHNuqnmVhTnlgXWQmkmC8BoMVRqFxJ2akf4Tl2f51FWND3HnNaslZXZ8XfqnDx8jiVzsIUndUHtMoG9OjXXpzqicOpd6FMa2ESV/GN68N6EoEaFLNQbC//paNOwq7gjv45slliDaFzUcfQR6hSMAVL95SmoQTlbaN8z2lZpOZFS+AtvnfmaqThs7eA+TO8liT5ugEyHQw/rHdolPJRzDCEf2mEZa1XTsXlM0nMt6EjKbT/dhigwq3/GbcDq6C8PYUlkf7E/imPC2axD4IFfxFWZGIV0n3rr5F+FVABHFGRv8HBMAHmVtFAuP0fMXFmjO7hpAPUOcMYRZoeswJGXN9QUlNaPfUUf3DNdeAVvnfI088yc9vbBlsINt4z0NMM9SK1v0Su2H2fbudXw+dOf4BnbH/rWWHfmoq7noitp9tjN5ey8veYTCWDRlm0xgJL4M8C9E2zvDDEMMmJXjRtcFGFrFJoZyJg4mRc9Pum376+KA8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
