travis:
  secure:
    BINSTAR_TOKEN: GD486MhzeArkE3GFlYjSbckev1xxAn2XUPznvVX0ZePwoSzoDt53motVTcPYhbJd/8+xc0rY1+JcVGpR6gumqENVxW4gbNBEDbVxm1/14cTsTBbl2I7s/G4xr/We10ueOCwjqq5ZvrbWL+yjjZv6DLFswJHUcSBmXYfm+XitHfTqAcD4lpJzuqMxXALOdC69y0u5vyIIe4DfQNfoqeXAGLDQBn50yUfqGAvnmGUXCbxuhx4pGcNnT1CPIuE6web/CZRvGJUHlVLag9H8/bSU4bHRxNYUpl8byiQfJXNzVFVRYo1Cb267TmqQ2q0ABzQVwYTe7hH5OdEMuQ38a2WRlRTuZfT5gOzJQdTJ70TQA/uCxtT1Rygg7+dy6BdT5v/2gToUabiUxHdoinWmBPWei+S5DKE4pnBHu2FtonWZYkXc9kNNSwaCT+ZLedE0jHq0q9gcPxM5bEp4PFlocYgyQGYfleCLEsU83zJAs5bgMwnPt2b1DZuAcjtnA54PbzFwciL220S8Ws8lYrKpzLi4DXwoIlZFm1j7AT6zlpy7E7XA72OC/37WyGuMzIb9UiNMKRrZ/8BV/3E44fDr7FKJyWQaEQ5/CzFEBtgSnxPf0ZAHaLo86uCXJsBWpaGZOvlAc1AiUc9NGr3d3xcvUt7o+3PD7bME5Pj3xJAE8znLgJM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
